// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package drive

import (
	"context"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO webapp.users (User_Name, Pass_Word_Hash, name)
VALUES ($1,
        $2,
        $3) RETURNING user_id, user_name, pass_word_hash, name, config, created_at, is_enabled
`

type CreateUsersParams struct {
	UserName     string `db:"user_name" json:"userName"`
	PassWordHash string `db:"pass_word_hash" json:"passWordHash"`
	Name         string `db:"name" json:"name"`
}

// insert new user
func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (WebappUser, error) {
	row := q.db.QueryRowContext(ctx, createUsers, arg.UserName, arg.PassWordHash, arg.Name)
	var i WebappUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PassWordHash,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.IsEnabled,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM webapp.users
WHERE user_id = $1
`

// delete a particular user
func (q *Queries) DeleteUsers(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUsers, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, user_name, pass_word_hash, name, config, created_at, is_enabled FROM webapp.users
WHERE user_id = $1
`

// get users of a particular user_id
func (q *Queries) GetUser(ctx context.Context, userID int64) (WebappUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i WebappUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PassWordHash,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.IsEnabled,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, user_name, pass_word_hash, name, config, created_at, is_enabled FROM webapp.users
ORDER BY user_name
`

// get all users ordered by the username
func (q *Queries) ListUsers(ctx context.Context) ([]WebappUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebappUser
	for rows.Next() {
		var i WebappUser
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.PassWordHash,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
